SELECT
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE,
NVL(SUM(e.MINUTOS_ESTANCIA), 0) AS TOTAL_MINUTOS,
NVL(SUM(e.MONTO_CARGO), 0) AS TOTAL_CARGOS
FROM RESIDENTE r
LEFT JOIN ESTANCIA e
ON e.ID_RESIDENTE = r.ID_RESIDENTE
AND e.ESTADO = 'CERRADA'
AND e.FECHA_SALIDA >= TIMESTAMP '2026-09-01 00:00:00'
AND e.FECHA_SALIDA <  TIMESTAMP '2026-10-01 00:00:00'
GROUP BY
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE
ORDER BY r.ID_RESIDENTE;



SELECT
ANIO,
MES,
TOTAL_MINUTOS,
TOTAL_CARGOS,
TOTAL_PAGOS,
ESTADO
FROM CIERRE_MENSUAL
ORDER BY ANIO, MES;


SELECT
ANIO,
MES,
ESTADO,
FECHA_CIERRE
FROM CIERRE_MENSUAL
ORDER BY ANIO, MES;


SELECT
ANIO,
MES,
FECHA_CIERRE,
USUARIO_CIERRE,
ESTADO
FROM CIERRE_MENSUAL
ORDER BY ANIO, MES;A
