SELECT
v.ID_VEHICULO,
v.PLACA,
tv.NOMBRE AS TIPO_VEHICULO,
cc.NOMBRE AS CATEGORIA_COBRO,
e.FECHA_ENTRADA,
ROUND(
(CAST(SYSTIMESTAMP AS DATE) - CAST(e.FECHA_ENTRADA AS DATE)) * 1440
) AS MINUTOS_TRANSCURRIDOS
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
INNER JOIN TIPO_VEHICULO tv
ON tv.ID_TIPO_VEHICULO = v.ID_TIPO_VEHICULO
INNER JOIN CATEGORIA_COBRO cc
ON cc.ID_CATEGORIA_COBRO = v.ID_CATEGORIA_COBRO
WHERE e.ESTADO = 'ABIERTA'
AND e.FECHA_SALIDA IS NULL
ORDER BY e.FECHA_ENTRADA;


SELECT
e.ID_ESTANCIA,
v.PLACA,
cc.NOMBRE AS CATEGORIA_COBRO,
e.FECHA_ENTRADA,
e.FECHA_SALIDA,
ROUND(
(
CAST(NVL(e.FECHA_SALIDA, SYSTIMESTAMP) AS DATE)
- CAST(e.FECHA_ENTRADA AS DATE)
) * 1440
) AS DURACION_MINUTOS,
t.MONTO_POR_MINUTO,
ROUND(
(
(
CAST(NVL(e.FECHA_SALIDA, SYSTIMESTAMP) AS DATE)
- CAST(e.FECHA_ENTRADA AS DATE)
) * 1440
) * t.MONTO_POR_MINUTO,
2
) AS IMPORTE_CALCULADO,
e.MONTO_CARGO AS IMPORTE_REGISTRADO
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
INNER JOIN CATEGORIA_COBRO cc
ON cc.ID_CATEGORIA_COBRO = v.ID_CATEGORIA_COBRO
INNER JOIN TARIFA t
ON t.ID_TARIFA = e.ID_TARIFA
WHERE e.ID_ESTANCIA = 9;


SELECT
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE || ' ' ||
NVL(r.APELLIDO_PATERNO, '') || ' ' ||
NVL(r.APELLIDO_MATERNO, '') AS RESIDENTE,
COUNT(e.ID_ESTANCIA) AS TOTAL_ESTANCIAS,
NVL(SUM(e.MINUTOS_ESTANCIA), 0) AS TOTAL_MINUTOS,
NVL(SUM(e.MONTO_CARGO), 0) AS TOTAL_CARGOS,
NVL((
SELECT SUM(pc.MONTO)
FROM PAGO_CARGO pc
WHERE pc.ID_RESIDENTE = r.ID_RESIDENTE
AND pc.TIPO_MOVIMIENTO = 'PAGO'
AND pc.FECHA_MOVIMIENTO >= TIMESTAMP '2026-09-01 00:00:00'
AND pc.FECHA_MOVIMIENTO <  TIMESTAMP '2026-10-01 00:00:00'
), 0) AS TOTAL_PAGOS,
NVL(SUM(e.MONTO_CARGO), 0)
-
NVL((
SELECT SUM(pc.MONTO)
FROM PAGO_CARGO pc
WHERE pc.ID_RESIDENTE = r.ID_RESIDENTE
AND pc.TIPO_MOVIMIENTO = 'PAGO'
AND pc.FECHA_MOVIMIENTO >= TIMESTAMP '2026-09-01 00:00:00'
AND pc.FECHA_MOVIMIENTO <  TIMESTAMP '2026-10-01 00:00:00'
), 0) AS SALDO
FROM RESIDENTE r
LEFT JOIN ESTANCIA e
ON e.ID_RESIDENTE = r.ID_RESIDENTE
AND e.ESTADO = 'CERRADA'
AND e.FECHA_ENTRADA >= TIMESTAMP '2026-09-01 00:00:00'
AND e.FECHA_ENTRADA <  TIMESTAMP '2026-10-01 00:00:00'
GROUP BY
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE,
r.APELLIDO_PATERNO,
r.APELLIDO_MATERNO
ORDER BY TOTAL_MINUTOS DESC;


SELECT
TRUNC(pc.FECHA_MOVIMIENTO) AS FECHA,
cc.CODIGO AS TIPO_COBRO,
cc.NOMBRE AS DESCRIPCION_TIPO,
COUNT(*) AS TOTAL_MOVIMIENTOS,
SUM(pc.MONTO) AS TOTAL_INGRESOS
FROM PAGO_CARGO pc
INNER JOIN ESTANCIA e
ON e.ID_ESTANCIA = pc.ID_ESTANCIA
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
INNER JOIN CATEGORIA_COBRO cc
ON cc.ID_CATEGORIA_COBRO = v.ID_CATEGORIA_COBRO
WHERE pc.TIPO_MOVIMIENTO = 'CARGO'
GROUP BY
TRUNC(pc.FECHA_MOVIMIENTO),
cc.CODIGO,
cc.NOMBRE
ORDER BY
FECHA,
TIPO_COBRO;


SELECT
tv.ID_TIPO_VEHICULO,
tv.CODIGO,
tv.NOMBRE AS TIPO_VEHICULO,
COUNT(*) AS TOTAL_ESTANCIAS,
ROUND(AVG(e.MINUTOS_ESTANCIA), 2) AS PROMEDIO_MINUTOS,
ROUND(AVG(e.MINUTOS_ESTANCIA) / 60, 2) AS PROMEDIO_HORAS
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
INNER JOIN TIPO_VEHICULO tv
ON tv.ID_TIPO_VEHICULO = v.ID_TIPO_VEHICULO
WHERE e.ESTADO = 'CERRADA'
AND e.MINUTOS_ESTANCIA IS NOT NULL
GROUP BY
tv.ID_TIPO_VEHICULO,
tv.CODIGO,
tv.NOMBRE
ORDER BY PROMEDIO_MINUTOS DESC;


SELECT
v.ID_VEHICULO,
v.PLACA,
COUNT(*) AS ESTANCIAS_ABIERTAS
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
WHERE e.ESTADO = 'ABIERTA'
AND e.FECHA_SALIDA IS NULL
GROUP BY
v.ID_VEHICULO,
v.PLACA
HAVING COUNT(*) > 1
ORDER BY ESTANCIAS_ABIERTAS DESC;


SELECT
e.ID_ESTANCIA,
v.PLACA,
e.FECHA_ENTRADA,
e.FECHA_SALIDA,
e.MINUTOS_ESTANCIA,
e.ESTADO,
CASE
WHEN e.FECHA_SALIDA < e.FECHA_ENTRADA
THEN 'SALIDA ANTERIOR A ENTRADA'
WHEN e.ESTADO = 'CERRADA' AND e.FECHA_SALIDA IS NULL
THEN 'ESTANCIA CERRADA SIN FECHA DE SALIDA'
WHEN e.ESTADO = 'ABIERTA' AND e.FECHA_SALIDA IS NOT NULL
THEN 'ESTANCIA ABIERTA CON FECHA DE SALIDA'
WHEN e.MINUTOS_ESTANCIA < 0
THEN 'MINUTOS NEGATIVOS'
END AS INCONSISTENCIA
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
WHERE
e.FECHA_SALIDA < e.FECHA_ENTRADA
OR (e.ESTADO = 'CERRADA' AND e.FECHA_SALIDA IS NULL)
OR (e.ESTADO = 'ABIERTA' AND e.FECHA_SALIDA IS NOT NULL)
OR e.MINUTOS_ESTANCIA < 0
ORDER BY e.ID_ESTANCIA;

SELECT
v.ID_VEHICULO,
v.PLACA,
tv.NOMBRE AS TIPO_VEHICULO,
cc.NOMBRE AS CATEGORIA_COBRO,
COUNT(e.ID_ESTANCIA) AS TOTAL_ESTANCIAS,
SUM(e.MINUTOS_ESTANCIA) AS TOTAL_MINUTOS,
ROUND(SUM(e.MINUTOS_ESTANCIA) / 60, 2) AS TOTAL_HORAS,
SUM(e.MONTO_CARGO) AS TOTAL_CARGOS
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
INNER JOIN TIPO_VEHICULO tv
ON tv.ID_TIPO_VEHICULO = v.ID_TIPO_VEHICULO
INNER JOIN CATEGORIA_COBRO cc
ON cc.ID_CATEGORIA_COBRO = v.ID_CATEGORIA_COBRO
WHERE e.ESTADO = 'CERRADA'
AND e.FECHA_ENTRADA >= TIMESTAMP '2026-09-01 00:00:00'
AND e.FECHA_ENTRADA <  TIMESTAMP '2026-10-01 00:00:00'
GROUP BY
v.ID_VEHICULO,
v.PLACA,
tv.NOMBRE,
cc.NOMBRE
ORDER BY TOTAL_MINUTOS DESC;


SELECT
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE || ' ' || NVL(r.APELLIDO_PATERNO, '') AS RESIDENTE,
COUNT(e.ID_ESTANCIA) AS TOTAL_ESTANCIAS,
NVL(SUM(e.MINUTOS_ESTANCIA), 0) AS TOTAL_MINUTOS,
NVL(SUM(e.MONTO_CARGO), 0) AS TOTAL_CARGOS
FROM RESIDENTE r
LEFT JOIN ESTANCIA e
ON e.ID_RESIDENTE = r.ID_RESIDENTE
AND e.ESTADO = 'CERRADA'
AND e.FECHA_ENTRADA >= TIMESTAMP '2026-09-01 00:00:00'
AND e.FECHA_ENTRADA <  TIMESTAMP '2026-10-01 00:00:00'
GROUP BY
r.ID_RESIDENTE,
r.NUMERO_RESIDENTE,
r.NOMBRE,
r.APELLIDO_PATERNO
ORDER BY TOTAL_MINUTOS DESC;



SELECT
v.PLACA,
SUM(e.MINUTOS_ESTANCIA) AS TOTAL_MINUTOS,
ROUND(SUM(e.MINUTOS_ESTANCIA) / 60, 2) AS TOTAL_HORAS
FROM ESTANCIA e
INNER JOIN VEHICULO v
ON v.ID_VEHICULO = e.ID_VEHICULO
WHERE e.ESTADO = 'CERRADA'
AND e.FECHA_ENTRADA >= TIMESTAMP '2026-09-01 00:00:00'
AND e.FECHA_ENTRADA <  TIMESTAMP '2026-10-01 00:00:00'
GROUP BY
v.ID_VEHICULO,
v.PLACA
ORDER BY TOTAL_MINUTOS DESC;
