-- ROL APLICACION

CREATE ROLE ROL_APLICACION;

GRANT CREATE SESSION TO ROL_APLICACION;

GRANT SELECT, INSERT, UPDATE ON VEHICULO TO ROL_APLICACION;

GRANT SELECT, INSERT, UPDATE ON RESIDENTE TO ROL_APLICACION;

GRANT SELECT, INSERT, UPDATE ON RESIDENTE_VEHICULO TO ROL_APLICACION;

GRANT SELECT ON TIPO_VEHICULO TO ROL_APLICACION;

GRANT SELECT ON CATEGORIA_COBRO TO ROL_APLICACION;

GRANT SELECT ON TARIFA TO ROL_APLICACION;

GRANT SELECT, INSERT, UPDATE ON ESTANCIA TO ROL_APLICACION;

GRANT SELECT, INSERT ON PAGO_CARGO TO ROL_APLICACION;

GRANT SELECT ON CIERRE_MENSUAL TO ROL_APLICACION;

GRANT SELECT ON CIERRE_MENSUAL_RESIDENTE TO ROL_APLICACION;



-- ROL REPORTES

CREATE ROLE ROL_REPORTES;

GRANT CREATE SESSION TO ROL_REPORTES;

GRANT SELECT ON TIPO_VEHICULO TO ROL_REPORTES;

GRANT SELECT ON CATEGORIA_COBRO TO ROL_REPORTES;

GRANT SELECT ON VEHICULO TO ROL_REPORTES;

GRANT SELECT ON TARIFA TO ROL_REPORTES;

GRANT SELECT ON ESTANCIA TO ROL_REPORTES;

GRANT SELECT ON PAGO_CARGO TO ROL_REPORTES;

GRANT SELECT ON CIERRE_MENSUAL TO ROL_REPORTES;

GRANT SELECT ON CIERRE_MENSUAL_RESIDENTE TO ROL_REPORTES;



-- ROL OPERACION

CREATE ROLE ROL_OPERACION;

GRANT CREATE SESSION TO ROL_OPERACION;

GRANT SELECT ON VEHICULO TO ROL_OPERACION;

GRANT SELECT ON RESIDENTE TO ROL_OPERACION;

GRANT SELECT ON ESTANCIA TO ROL_OPERACION;

GRANT SELECT ON PAGO_CARGO TO ROL_OPERACION;

GRANT SELECT ON CIERRE_MENSUAL TO ROL_OPERACION;

GRANT SELECT ON CIERRE_MENSUAL_RESIDENTE TO ROL_OPERACION;

GRANT SELECT ON AUDITORIA_OPERACION TO ROL_OPERACION;

GRANT UPDATE (ESTADO, FECHA_MODIFICACION)
ON ESTANCIA TO ROL_OPERACION;



-- USUARIO APLICACION

CREATE USER USUARIO_APLICACION
IDENTIFIED BY "CAMBIAR_PASSWORD_APLICACION"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT LOCK;

GRANT ROL_APLICACION TO USUARIO_APLICACION;

ALTER USER USUARIO_APLICACION PASSWORD EXPIRE;



-- USUARIO REPORTES

CREATE USER USUARIO_REPORTES
IDENTIFIED BY "CAMBIAR_PASSWORD_REPORTES"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT LOCK;

GRANT ROL_REPORTES TO USUARIO_REPORTES;

ALTER USER USUARIO_REPORTES PASSWORD EXPIRE;



-- USUARIO OPERACION

CREATE USER USUARIO_OPERACION
IDENTIFIED BY "CAMBIAR_PASSWORD_OPERACION"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT LOCK;

GRANT ROL_OPERACION TO USUARIO_OPERACION;

ALTER USER USUARIO_OPERACION PASSWORD EXPIRE;

